/**:
  ros__parameters:
    drone:
      m: 3.146
      l: 0.265
      MoiArray: [0.060, 0.060, 0.080]
      motor_const: 1.386e-7
      moment_const: 0.01569

    dob:
      dob_looptime: 0.010
      eps_f: 0.1
      eps_tau: 0.1

    topic_names:
      odom_in: "/mavros/local_position/odom"
      filtered_odom: "/hgdo/filtered_odom"
      actual_rpm: "/uav/actual_rpm"
      dob_wrench: "/hgdo/wrench"