/**:
  ros__parameters:
    dynamic_param:
      m: 3.146
      MoiArray: [0.06, 0.06, 0.08]
      moment_ff: true
      com_offset: [-0.01043,0.00496]

    drone_param:
      arm_length: 0.265
      motor_const: 1.386e-07
      moment_const: 0.01569
      rotor_max: 7300.0     # Maximum RPM
      rotor_min: 2000.0     # Minimum RPM
      acc_max: 15000.0    # Acc 15 krpm/s
      acc_min: 15000.0    # Dec 15 krpm/s
      cmd_lpf_cutoff: 10.0  # LPF cutoff frequency [Hz] for cmd output

    nmpc_param:
      t_horizon: 1.0
      n_nodes: 20
      QArray: [ 2.0, 2.0, 10.0,        # px, py, pz
                1.0, 1.0, 7.0,        # vx, vy, vz
                20.0, 20.0, 20.0, 20.0,   # qw, qx, qy, qz
                7.0, 7.0, 7.0]     # wx, wy, wz
      R: [10.0]     # u1...u6

    topic_names:
      cmd_topic: '/uav/cmd_raw'
      rc_topic: '/mavros/rc/in'
      base_line_control_topic: '/nmpc/control'
      filtered_odom_topic: '/hgdo/filtered_odom'
      ref_topic: '/nmpc/ref'
      dob_wrench_topic: '/hgdo/wrench'