/**:
  ros__parameters:
    constraint:
      vxy_max: 0.3
      vz_max: 0.5
      dpsi_dt_max: 0.2

    gain_param:
      KpTransArray: [2.7, 2.7, 2.7]
      KpOriArray: [3.0, 3.0, 0.18]
      KdOriArray: [0.4, 0.52, 0.15]
      AccelMaxArray: [1, 1, 1]

    dynamic_param:
      m: 3.0
      MoiArray: [0.06, 0.06, 0.08]

    drone_param:
      arm_length: 0.265
      rotor_const: 1.465e-07
      moment_const: 0.01569
      T_max: 9.376
      T_min: 0.586

    sensor_time_param:
      timeout:
        rc: 0.10
        odom: 0.10
        do: 0.10